### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by sandorvasas** [oxequa/realize#167]
I'm on Ubuntu 16.04, run `realize start --run --build --vet` from project root folder. I see realize logs, detecting changes to the sources, however the go app itself never starts. Neither I know how could I see the output from it (if the app started), since in the console I see _only_ Realize's logs.

**Comment by Asoseil** [comment]
do you print something in your program? Could you add a sample script?

**Comment by sandorvasas** [comment]
Just a basic webserver example:
```
package main

import (
	"fmt"
	"net/http"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "Hello from Go! %s", r.URL.Path)
	})

	fmt.Println("Listening..")
	err := http.ListenAndServe(":8080", nil)
	if err != nil {
		fmt.Println("ERROR ", err)
	}
}

```

**Comment by Asoseil** [comment]
you should see "listening" as printed text after "Running", doesn't it works for you?

**Comment by conventi** [comment]
@sandorvasas did you solved? Let us know so that we can help you or close this issue.

**Comment by brietsparks** [comment]
@sandorvasas, in .realize.yml, make sure path is set and run status is true:
```
# ...
schema:
- name: myproject
  path: /path/to/project/files
  commands:
      run:
        status: true
# ...
```
