### ISSUE TITLE
realize: command not found

### ISSUE THREAD

**Issue by DanielSokil** [oxequa/realize#173]
I ran `go get github.com/oxequa/realize`.
It successfully installed and tried to run `realize start` in my project directory.

go1.10.1 linux/amd64

Thanks Ahead For Any Help/Suggestions.

**Comment by mingrammer** [comment]
Show your `$PATH`

**Comment by DanielSokil** [comment]
@mingrammer Here is what I have in my `.profile` file in `$HOME` directory `export PATH=$PATH:/usr/local/go/bin`.
This is the only thing I exported during go installation.

**Comment by mingrammer** [comment]
How about `$GOPATH`? the go get command installs the go package into `$GOPATH/src/`

**Comment by DanielSokil** [comment]
Here is what I get from `go env`
```
GOPATH="/home/danielsokil/go"
GORACE=""
GOROOT="/usr/local/go"
```

**Comment by mingrammer** [comment]
Ok, so just append the `/home/danielsokil/go` to your `PATH` in .profile, then re-login to shell.

**Comment by DanielSokil** [comment]
@mingrammer Thank You For Your Help. 
I have set `PATH` to `export PATH=$PATH:/usr/local/go/bin:/home/danielsokil/go/bin`

**Comment by mingrammer** [comment]
Congrats!

**Comment by david-castaneda** [comment]
The following worked for me:
- Inside your project directory ```export GOBIN=$PWD/.bin```
- Inside your project directory ```.bin/realize start```
