### ISSUE TITLE
Using github.com/robcapo fork in main app

### ISSUE THREAD

**Issue by robcapo** [oxequa/realize#185]
When you merged my [PR 184](https://github.com/oxequa/realize/pull/184) you also merged the [import to my fork](https://github.com/oxequa/realize/blob/master/realize.go#L5) in `package main`

This will cause all changes in this repo's `realize/` directory to have no impact on the main app.

**Comment by robcapo** [comment]
I don't believe I have permission to create branches on this repo, so I won't be able to make a PR

**Comment by Asoseil** [comment]
Fixed, thanks
