### ISSUE TITLE
Cannot build realize because of a dependency issue in go-siris/siris

### ISSUE THREAD

**Issue by francoispqt** [oxequa/realize#186]
Hi,

Trying to build realize using dep but getting errors because of a dependency issue in go-siris. 

Steps: 
```bash
git clone github.com/oxequa/realize && cd realize && dep ensure && go install
```

Result: 
```bash
# github.com/oxequa/realize/vendor/github.com/go-siris/siris/core/errors
vendor/github.com/go-siris/siris/core/errors/errors.go:35:22: multiple-value uuid.NewV4() in single-value context
```

As far as I see, it's only used in one place. Can we just copy the errors package from `go-siris` directly into an `errors.go` file in realize and fix the error?

Thanks

**Comment by Asoseil** [comment]
Fixed, thank you
