### ISSUE TITLE
bash: realize: command not found

### ISSUE THREAD

**Issue by aibrahim3546** [oxequa/realize#223]
this is my `go env`

<img width="407" alt="screen shot 2018-10-30 at 3 58 31 pm" src="https://user-images.githubusercontent.com/31366174/47703940-da28a980-dc5c-11e8-823a-69a5892d3747.png">

I do as follow:
`go get github.com/oxequa/realize`

then when I use `realize start`
I hit this error: `bash" realize:command not found`

**Comment by hvze** [comment]
Make sure `realize` is in your `$PATH` variable. 
(try putting `export PATH=$GOPATH/bin:$PATH` in your `.zshrc` or respective config file

**Comment by Asoseil** [comment]
thanks for the support and for the reports, in the last months we had some company changes but in the first trimester 2019 we will release a new version

**Comment by david-castaneda** [comment]
The following worked for me:

Inside your project directory export GOBIN=$PWD/.bin
Inside your project directory .bin/realize start
