### ISSUE TITLE
Adapt go modules for fixing dependencies

### ISSUE THREAD

**Issue by yyh-gl** [oxequa/realize#266]
# Problem

The dependencies is broken because there was a big change in [`urfave/cli`](https://github.com/urfave/cli).

I show related links below:

- https://github.com/oxequa/realize/issues/262.
- https://github.com/urfave/cli/issues/1029

# Environment
- macOS Mojave 10.14.4
- Golang: 1.14.2

# Proposal solution

- Adapt go modules
- Change path of `urfave/cli` package.

PR is [here](https://github.com/oxequa/realize/pull/265).

**Comment by yyh-gl** [comment]
The [PR](https://github.com/oxequa/realize/pull/265) that resolve this issue was merged.
Thanks for review.

**Comment by irvinlim** [comment]
Thanks @conventi for merging this. Is it possible to get a new release tag so that `go get github.com/oxequa/realize` works out of the box?

For anyone else, you can append the commit hash to `go get` as follows to get a specific commit:

```
go get github.com/oxequa/realize@498ce46d1b223185254598c51d88718179abb71e
```
